apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ms-pet
spec:
  replicas: 1
  selector:
      matchLabels:
        app: ms-pet
  template:
    metadata:
      labels:
        app: ms-pet
    spec:
      containers:
        - image: rsobook/ms-pet:2.0.1
          name: ms-pet
          env:
            - name: PORT
              value: '80'
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://ms-etcd:2379
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://ms-etcd:2379
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://ms-database:5432/rsobook-pet
          ports:
          - containerPort: 80
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10